version: "3.8" 
services: 
  mongodb: 
    image: "mongo" 
    volumes: 
      - data:/data/db
    environment:
      - MONGO_URL=mongodb+srv://superuser:password@cluster0.esjdlvi.mongodb.net/projectApp
  backend: 
    build: ./server 
    ports: 
      - "8080:8080" 
    volumes: 
      - logs:/app/logs 
      - ./server:/app 
      - /app/node_modules 
    depends_on: 
      - mongodb 
  frontend: 
    build: ./frontend 
    ports: 
      - "3000:3000" 
    volumes: 
      - ./frontend/src:/app/src 
    stdin_open: true 
    tty: true 
    depends_on: 
      - backend
volumes: 
  data: 
  logs: